---
- name: APT Dist-Upgrade
  apt:
    upgrade: dist
    autoremove: true
    dpkg_options: force-confold,force-confdef
  register: apt_upgrade

- name: Reboot after APT Dist-Upgrade  # noqa no-handler
  when:
  - apt_upgrade.changed or system_upgrade_reboot == 'always'
  - system_upgrade_reboot != 'never'
  reboot:
    # Can take a long time if applying firmware upgrades at the same time
    reboot_timeout: 1800
